from django import forms
from django.forms.widgets import DateTimeInput

OPCOES_CHOICES = (
    ('C', 'Conforme'),
    ('NC', 'Não conforme'),
    ('NA', 'Não se aplica'),
)
class MeuFormulario(forms.Form):
    usina = forms.CharField(max_length=50)
    datainsp = forms.CharField(widget=forms.TextInput(attrs={'type':'date'}))
    opcoes = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes2 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes3 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes4 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes5 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes6 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes7 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes8 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes9 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes10 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes11 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes12 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes13 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes14 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes15 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes16 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes17 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes18 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes19 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes20 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes21 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes22 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes23 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes24 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes25 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes26 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes27 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes28 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes29 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes30 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    opcoes31 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)  
    opcoes32 = forms.ChoiceField(choices=OPCOES_CHOICES, widget=forms.RadioSelect)
    observacoes1 = forms.CharField(max_length=60, required=False) 
    observacoes2 = forms.CharField(max_length=60, required=False) 
    observacoes3 = forms.CharField(max_length=60, required=False) 
    observacoes4 = forms.CharField(max_length=60, required=False) 
    observacoes5 = forms.CharField(max_length=60, required=False) 
    observacoes6 = forms.CharField(max_length=60, required=False) 
    observacoes7 = forms.CharField(max_length=60, required=False) 
    observacoes8 = forms.CharField(max_length=60, required=False) 
    observacoes9 = forms.CharField(max_length=60, required=False) 
    observacoes10 = forms.CharField(max_length=60, required=False) 
    observacoes11 = forms.CharField(max_length=60, required=False) 
    observacoes12 = forms.CharField(max_length=60, required=False) 
    observacoes13 = forms.CharField(max_length=60, required=False) 
    observacoes14 = forms.CharField(max_length=60, required=False) 
    observacoes15 = forms.CharField(max_length=60, required=False) 
    observacoes16 = forms.CharField(max_length=60, required=False) 
    observacoes17 = forms.CharField(max_length=60, required=False) 
    observacoes18 = forms.CharField(max_length=60, required=False) 
    observacoes19 = forms.CharField(max_length=60, required=False) 
    observacoes20 = forms.CharField(max_length=60, required=False) 
    observacoes21 = forms.CharField(max_length=60, required=False) 
    observacoes22 = forms.CharField(max_length=60, required=False) 
    observacoes23 = forms.CharField(max_length=60, required=False) 
    observacoes24 = forms.CharField(max_length=60, required=False) 
    observacoes25 = forms.CharField(max_length=60, required=False) 
    observacoes26 = forms.CharField(max_length=60, required=False) 
    observacoes27 = forms.CharField(max_length=60, required=False) 
    observacoes28 = forms.CharField(max_length=60, required=False) 
    observacoes29 = forms.CharField(max_length=60, required=False) 
    observacoes30 = forms.CharField(max_length=60, required=False) 
    observacoes31 = forms.CharField(max_length=60, required=False) 
    observacoes32 = forms.CharField(max_length=60, required=False) 