from django.db import models

# Create your models here.
OPCOES_CHOICES = (
    ('Conforme', 'Conforme'),
    ('Não conforme', 'Não conforme'),
    ('Não se aplica', 'Não se aplica'),
)
class MeuFormulario(models.Model):
    usina = models.CharField(max_length=50)
    datainsp = models.DateField()
    opcoes = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes2 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes3 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes4 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes5 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes6 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes7 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes8 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes9 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes10 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes11 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes12 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes13 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes14 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes15 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes16 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes17 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes18 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes19 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes20 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes21 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes22 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes23 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes24 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes25 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes26 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes27 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes28 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes29 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes30 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes31 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    opcoes32 = models.CharField(max_length=13, choices=OPCOES_CHOICES)
    observacoes1 = models.CharField(max_length=60, blank=True) 
    observacoes2 = models.CharField(max_length=60, blank=True) 
    observacoes3 = models.CharField(max_length=60, blank=True) 
    observacoes4 = models.CharField(max_length=60, blank=True) 
    observacoes5 = models.CharField(max_length=60, blank=True) 
    observacoes6 = models.CharField(max_length=60, blank=True) 
    observacoes7 = models.CharField(max_length=60, blank=True) 
    observacoes8 = models.CharField(max_length=60, blank=True) 
    observacoes9 = models.CharField(max_length=60, blank=True) 
    observacoes10 = models.CharField(max_length=60, blank=True)  
    observacoes11 = models.CharField(max_length=60, blank=True) 
    observacoes12 = models.CharField(max_length=60, blank=True) 
    observacoes13 = models.CharField(max_length=60, blank=True) 
    observacoes14 = models.CharField(max_length=60, blank=True) 
    observacoes15 = models.CharField(max_length=60, blank=True) 
    observacoes16 = models.CharField(max_length=60, blank=True) 
    observacoes17 = models.CharField(max_length=60, blank=True) 
    observacoes18 = models.CharField(max_length=60, blank=True) 
    observacoes19 = models.CharField(max_length=60, blank=True) 
    observacoes20 = models.CharField(max_length=60, blank=True) 
    observacoes21 = models.CharField(max_length=60, blank=True) 
    observacoes22 = models.CharField(max_length=60, blank=True) 
    observacoes23 = models.CharField(max_length=60, blank=True) 
    observacoes24 = models.CharField(max_length=60, blank=True) 
    observacoes25 = models.CharField(max_length=60, blank=True) 
    observacoes26 = models.CharField(max_length=60, blank=True) 
    observacoes27 = models.CharField(max_length=60, blank=True) 
    observacoes28 = models.CharField(max_length=60, blank=True) 
    observacoes29 = models.CharField(max_length=60, blank=True) 
    observacoes30 = models.CharField(max_length=60, blank=True) 
    observacoes31 = models.CharField(max_length=60, blank=True) 
    observacoes32 = models.CharField(max_length=60, blank=True) 
   