# Generated by Django 3.2.8 on 2021-11-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes1',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes10',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes11',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes12',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes13',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes14',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes15',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes16',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes17',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes18',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes19',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes2',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes20',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes21',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes22',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes23',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes24',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes25',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes26',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes27',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes28',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes29',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes3',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes30',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes31',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes32',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes4',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes5',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes6',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes7',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes8',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='meuformulario',
            name='observacoes9',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
